import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Sidebar from "@/components/shared/sidebar";
import Navbar from "@/components/shared/navbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Payouts",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <div className="flex h-[100svh] fixed w-screen">
                    <Sidebar />
                    <div className="flex flex-col w-full">
                        <Navbar />
                        <div className="overflow-auto ml-[56px] sm:ml-0">
                            {children}
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
